### ISSUE TITLE
Is there a utility for exporting an XER file directly from the DB

### ISSUE THREAD

**Issue by kirlev** [chipnetics/xertools#1]
Is there a utility that can fetch a project's data from the DB and convert it to a XER file without going through P6?

**Comment by chipnetics** [comment]
Hi, I haven't seen any tool that directly reads from P6 SQLite database and generates a XER.

Are you looking to just automatically extract XER files from P6? (without having to manually go through the program itself?).  I have some scripts for that....

**Comment by kirlev** [comment]
Yes, exactly so, I thought it might be part of the `xertools` package.
